### ISSUE TITLE
PSI

### ISSUE THREAD

**Issue by TTitcombe** [OpenMined/PyVertical#2]
## Description
Apply Private Set Intersection (PSI) to link vertically split data from multiple sources

## Why?
To complete this Epic, we need to generate datasets which simulate a real-world setting: datapoints not shared by both datasets, data appearing in random orders, IDs which link data. We then apply PSI to re-link the data

## Breakdown

- [x] Jumble data #7 
- [x] Add unique IDs to data #8
- [x] Randomly missing data #9
- [x] Add PSI code #13 
- [x] Apply PSI to re-link data #34 

## Who else?
May require changes to https://github.com/OpenMined/PSI

**Comment by xexiyong** [comment]
Hi, I have a question, the PSI solution will be written into this repo in the near future?

**Comment by TTitcombe** [comment]
Hi @xexiyong. The PSI code is in the repo and we're in the process of demonstrating how it can be used to train vertically partitioned data (see issue #34). It shouldn't be too long 🤞
