### ISSUE TITLE
Integrate with syft

### ISSUE THREAD

**Issue by TTitcombe** [OpenMined/PyVertical#28]
## What?
The current implementation of data loaders and datasets is quite hacky.
We should integrate existing syft functionality and extend it to make Vertically-partitioned dataset
a robust class, making it easy for anyone to apply PyVertical to any dataset

## Breakdown
- [x] Build on `syft.fl.BaseDataset` to create a dataset which holds partitions and may hold either data or targets. This should extend `PyVertical`'s `VerticalDataset` to include `syft` functionality of ownership #47 
- [x] Create a function `dataset_partition` which partitions a dataset, sends the partitioned datasets to the correct worker, and returns a `syft.fl.FederatedDataset` of partitioned datssets. This builds on the current `partition_dataset` function in `PyVertical`, and is similar to `syft.fl.dataset_federate` #48 
- [x] Replace `PartitionDistributingDataLoader` with a dataloader which takes a `syft.fl.FederatedDataset`. This should extend `syft.fl.FederatedDataLoader` to account for datasets which may not contain data or targets #49 
- [x] Integrate with PSI #50 
- [x] Encrypt unique IDs #54 

## Additional Context
This will developed simultaneously with the extended PyVertical demonstration (#25), so to avoid breaking changes existing dataloaders/data splitters should be kept until this issue is complete

**Comment by TTitcombe** [comment]
cc @tudorcebere from PySyft

**Comment by TTitcombe** [comment]
closing as issues do not align with current roadmap for `syft 0.3.0`
