### ISSUE TITLE
Simple Vertically Partitioned Model

### ISSUE THREAD

**Issue by TTitcombe** [OpenMined/PyVertical#3]
## Description
Implement a simple SplitNN using `syft` which trains on vertically split data provided by multiple data holders

## Why?
This may be the first open source implementation of a split model trained on vertically partitioned data. Training the model successfully is a complex process, which requires a custom data pipeline and model architecture.

This epic is the first stage of the project: The data will be ordered (no need for PSI) and we will send data labels away from the data holders

## Breakdown
Provide a bulleted or numbered list of how you might break this epic down into smaller issues.

- [x] Implement function to vertically split dataset (2 data holders/ 1 split) #4 
- [ ] Implement vertically split data loader #5 
- [x] Develop vertically split SplitNN #6 

## Who else?
May require changes in [PySyft](https://github.com/OpenMined/PySyft)
